FROM node:20-alpine AS production

ARG REDIS_URL=redis://redis:6379
ENV REDIS_URL=${REDIS_URL}

RUN apk add --no-cache postgresql-client

WORKDIR /server

RUN npm install pnpm@10.11.1 -g

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json .npmrc ./
COPY apps/backend/package.json ./apps/backend/

RUN pnpm install --frozen-lockfile

COPY apps/backend ./apps/backend

RUN cd /server/apps/backend && pnpm build

EXPOSE 9000

ENTRYPOINT ["./start.sh"]
